<a href="https://colab.research.google.com/github/EAsencios/DEEP-LEARING/blob/master/Copy_of_Untitled4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [ ]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [ ]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [ ]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[81 92 77 56 85 67]


In [ ]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1) 

[0.5601335  0.14639169 0.55426888 0.55652911 0.43165343 0.53039173]


In [ ]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.5601335  2.14639169 2.55426888 2.55652911 2.43165343 2.53039173]


In [ ]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[243 276 231 168 255 201]


In [ ]:
feature = np.arange(6, 21)
print(feature)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
label = (3)*(feature)+4
print(label)

[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [ ]:
noise = np.random.random(15)*4 -2
print(noise)

[ 1.0623649   1.73758807 -1.96808687  1.48345653 -0.71888058 -1.61476933
  0.32818509  0.71356411  1.12302375 -1.89451312 -1.36392627  0.40895402
 -0.24161024 -1.76040546 -1.1732549 ]


In [ ]:
label = label + noise
print(label)

[23.0623649  26.73758807 26.03191313 32.48345653 33.28111942 35.38523067
 40.32818509 43.71356411 47.12302375 47.10548688 50.63607373 55.40895402
 57.75838976 59.23959454 62.8267451 ]
